stages:
  - test

sast:
  stage: test
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/sast:latest
  script:
    - curl -L https://github.com/OWASP/railsgoat/archive/main.zip -o railsgoat.zip
    - unzip railsgoat.zip
    - cd railsgoat-main
    - /analyze -f gl-sast -o gl-sast-report.json .
  artifacts:
    reports:
      sast: gl-sast-report.json
