# This file is a template, and might need editing before it works on your project.
# This template moved to Jobs/SAST.gitlab-ci.yml in GitLab 14.0
# Issue: https://gitlab.com/gitlab-org/gitlab/-/issues/292977

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test

variables:
  SAST_ANALYZER_IMAGE: registry.gitlab.com/gitlab-org/security-products/analyzers/sast:latest
  SAST_EXCLUDED_PATHS: "vendor/*"

sast:
  stage: test
  dependencies:
    - compile
  artifacts:
    reports:
      sast: gl-sast-report.json
  script:
    - mvn compile
    - sast

before_script:
  - apt-get update -qq && apt-get install -y -qq curl unzip

cache:
  paths:
    - .m2/repository

