image-build:
  stage: build
  script:
    - docker build -t myapp:$CI_COMMIT_SHORT_SHA .
    - docker save myapp:$CI_COMMIT_SHORT_SHA | gzip > myapp-$CI_COMMIT_SHORT_SHA.tar.gz
  artifacts:
    paths:
      - myapp-$CI_COMMIT_SHORT_SHA.tar.gz
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

trivy-scan:
  stage: test
  image: docker/docker-bench-security
  script:
    - gunzip -c myapp-$CI_COMMIT_SHORT_SHA.tar.gz | docker load
    - trivy --exit-code 1 myapp:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_MERGE_REQUEST_ID
